database:
    enabled: false
    host: ''
    database: ''
    username: ''
    password: ''
    port: '3306'

general:
    check-updates: true

messages:
    prefix: "&7[&6PlayerLogger&7] "
    unknown-command: "{prefix}Unknown Command. Please type &6/playerlogger help"
    playeronly-command: "{prefix}&cThis command can only be executed by a player."
    no-permission: "{prefix}&cYou do not have permission to execute this command."


